import { randomUUID } from "node:crypto";
import { importLocalDirectory, readImportedFile, type ImportResult } from "../import/localImporter.ts";
import { detectLanguages } from "../import/languageDetector.ts";
import { analyzeSource } from "../sast/engine.ts";
import { scanForSecrets } from "../secrets/mask.ts";
import { analyzeDependencies } from "../dependencies/analyzer.ts";
import { FixtureVulnerabilityProvider, OfflineVulnerabilityProvider } from "../dependencies/providers.ts";
import { fromDependencyFinding, fromSastFinding, fromSecretFinding, type Finding, type Evidence } from "../findings/model.ts";
import { correlateFindings } from "../correlation/engine.ts";
import { scoreProject, type ProjectRiskSummary } from "../risk/engine.ts";
import { buildJsonReport, buildMarkdownReport, buildHtmlReport } from "../reports/engine.ts";
import { analyzeArchitecture, type ArchitectureReport } from "../analyzers/architecture/index.ts";
import { analyzePerformance, type PerformanceReport } from "../analyzers/performance/index.ts";
import { MockAIProvider, type AIAnalysisResult, type AIProvider } from "../ai/provider.ts";
import { redactSensitiveData } from "../ai/redaction.ts";

export interface AnalysisResult { id:string; projectId:string; projectName:string; status:"COMPLETED"|"FAILED"; startedAt:string; finishedAt:string; duration:number; import:ImportResult; languages:ReturnType<typeof detectLanguages>; architecture:ArchitectureReport; performance:PerformanceReport; ai:AIAnalysisResult; findings:Finding[]; risk:ProjectRiskSummary; reports:{json:string;markdown:string;html:string}; limitations:string[]; }
function aiFindings(ai:AIAnalysisResult):Finding[]{return ai.findings.map((f,i)=>({id:`ai:${i}:${f.file??"project"}:${f.line??"?"}`,title:f.title,category:f.category,severity:f.severity,confidence:f.confidence,cwe:null,file:f.file??"",line:f.line,remediation:f.remediation,status:f.confidence==="high"?"CONFIRMED":f.confidence==="medium"?"LIKELY":"POTENTIAL",evidence:[{source:"ai",ruleId:"AI-ANALYSIS",detail:f.explanation}]}));}
export class AnalysisPipeline { constructor(private ai:AIProvider=new MockAIProvider(),private dependencyProvider="fixture" as "fixture"|"offline"){}
 async run(projectId:string,projectName:string,baseDir:string):Promise<AnalysisResult>{const started=Date.now(),startedAt=new Date().toISOString(),analysisId=randomUUID();const imp=importLocalDirectory(baseDir);const languages=detectLanguages(imp.files.map(f=>f.relativePath));const findings:Finding[]=[];
  for(const f of imp.files){if(f.sizeBytes>2_000_000||! /\.(ts|tsx|js|jsx|mjs|cjs|py)$/.test(f.relativePath))continue;try{const code=readImportedFile(baseDir,f.relativePath);for(const x of analyzeSource(code,f.relativePath))findings.push(fromSastFinding(x));for(const x of scanForSecrets(code,f.relativePath))findings.push(fromSecretFinding(x));}catch{}}
  let depReport: Awaited<ReturnType<typeof analyzeDependencies>>={totalDependencies:0,findings:[],limitations:["Manifesto de dependências não encontrado."]};const manifest=imp.files.find(f=>f.relativePath==="package.json");if(manifest){try{depReport=await analyzeDependencies(readImportedFile(baseDir,manifest.relativePath),manifest.relativePath,this.dependencyProvider==="fixture"?new FixtureVulnerabilityProvider():new OfflineVulnerabilityProvider());for(const d of depReport.findings)for(const f of fromDependencyFinding(d,manifest.relativePath))findings.push(f);}catch{depReport.limitations.push("package.json inválido ou inacessível.");}}
  const architecture=analyzeArchitecture(baseDir,imp.files),performance=analyzePerformance(baseDir,imp.files);const archFindings:Finding[]=architecture.risks.map((r,i)=>({id:`architecture:${i}`,title:r,category:"Architecture Risk",severity:"MEDIUM",confidence:"medium",cwe:null,file:"",line:null,remediation:"Revise a separação de responsabilidades e o acoplamento identificado.",status:"LIKELY",evidence:[{source:"architecture",ruleId:"ARCH-RISK",detail:r}]}));const perfFindings:Finding[]=performance.findings.map(f=>({id:`${f.ruleId}:${f.file}:${f.line??"?"}`,title:f.title,category:"Performance",severity:f.severity,confidence:f.confidence,cwe:null,file:f.file,line:f.line,remediation:f.remediation,status:f.confidence==="high"?"CONFIRMED":f.confidence==="medium"?"LIKELY":"POTENTIAL",evidence:[{source:"performance",ruleId:f.ruleId,detail:f.evidence}]}));findings.push(...archFindings,...perfFindings);
  const aiContext={projectName,summary:`${findings.length} findings antes da IA`,findings:JSON.parse(redactSensitiveData(JSON.stringify(findings))),architecture:JSON.parse(redactSensitiveData(JSON.stringify(architecture)))};const ai=await this.ai.analyze(aiContext);findings.push(...aiFindings(ai));const correlated=correlateFindings(findings),risk=scoreProject(correlated),finishedAt=new Date().toISOString();const reports={json:buildJsonReport({projectName,generatedAt:finishedAt,findings:correlated,risk}),markdown:buildMarkdownReport({projectName,generatedAt:finishedAt,findings:correlated,risk}),html:buildHtmlReport({projectName,generatedAt:finishedAt,findings:correlated,risk})};return{id:analysisId,projectId,projectName,status:"COMPLETED",startedAt,finishedAt,duration:Date.now()-started,import:imp,languages,architecture,performance,ai,findings:correlated,risk,reports,limitations:[...imp.rejected.map(r=>`Entrada rejeitada: ${r.relativePath} (${r.reason}).`),...depReport.limitations,...architecture.limitations,...performance.limitations,...ai.limitations]};}
}
